---
- hosts: balancer
  become: yes
  vars:
    - haproxy_backend_servers:
      - name: core01.toolsthatmatter.com
        address: 165.227.133.199:31989
      - name: core02.toolsthatmatter.com
        address: 138.197.189.247:31989
      - name: core03.toolsthatmatter.com
        address: 138.197.179.107:31989
  roles:
    - geerlingguy.haproxy
