---
- hosts: balancer
  become: yes
  vars:
    - nfs_exports: ["/var/pub/www 165.227.0.0/16(rw,sync)"]
    - haproxy_dns_name: "{{ inventory_hostname }}"
    - ingress_port: 30987
    - haproxy_backend_servers:
      - name: core01.toolsthatmatter.com
        address: 165.227.175.163:{{ ingress_port }}
      - name: core02.toolsthatmatter.com
        address: 165.227.175.167:{{ ingress_port }}
      - name: core03.toolsthatmatter.com
        address: 165.227.168.211:{{ ingress_port }}
  roles:
    - geerlingguy.haproxy
    - geerlingguy.nfs
  tasks:
    - name: ensure proper permissins for export dir
      file:
        path: /var/pub/www/
        state: directory
        owner: nobody
        group: nogroup
    - name: create example file
      copy:
        dest: /var/pub/www/index.html
        content: "Foo\n"
        mode: 0755
        owner: nobody
        group: nogroup
