---
- hosts: balancer
  become: yes
  vars:
    - haproxy_dns_name: "{{ inventory_hostname }}"
    - ingress_port: 30987
    - haproxy_backend_servers:
      - name: core01.toolsthatmatter.com
        address: 165.227.175.163:{{ ingress_port }}
      - name: core02.toolsthatmatter.com
        address: 165.227.175.167:{{ ingress_port }}
      - name: core03.toolsthatmatter.com
        address: 165.227.168.211:{{ ingress_port }}
  roles:
    - geerlingguy.haproxy
  tasks:
    - name: install nginx-ingress
      shell: helm upgrade --install demo stable/nginx-ingress --set controller.service.type=NodePort,controller.service.nodePorts.http={{ ingress_port }}
      run_once: true
      ignore_errors: true
      delegate_to: localhost
      become: no
