---
- hosts: balancer
  vars:
    - nfs_exports: ["/var/pub/www 165.227.0.0/16(rw,sync)"]
  roles:
    - geerlingguy.nfs
  tasks:
    - name: ensure proper permissins for export dir
      file:
        path: /var/pub/www/
        state: directory
        owner: nobody
        group: nogroup
    - name: create example file
      copy:
        dest: /var/pub/www/index.html
        content: "Foo\n"
        mode: 0755
        owner: nobody
        group: nogroup
