apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: cluster.toolsthatmatter.com
    path: "/var/pub/www"
