---

- name: ensure k8s manifests directory exist
  file:
    path: /etc/kubernetes/manifests
    owner: root
    group: root
    mode: 0755
    state: directory

- name: configure k8s Api server / Proxy / Kubeconfig
  template:
    src: "{{k8s_template_dir}}/generate_yaml.j2"
    dest: "{{item.dest}}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items:
    - { yaml: "{{k8s_kube_apiserver}}", dest: '/etc/kubernetes/manifests/kube-apiserver.yaml' }
    - { yaml: "{{k8s_kube_proxy_workers}}", dest: '/etc/kubernetes/manifests/kube-proxy.yaml' }
    - { yaml: "{{k8s_worker_kubeconfig}}", dest: '/etc/kubernetes/worker-kubeconfig.yaml' }
  notify: restart kubelet