---

- name: waiting api port to be open
  wait_for:
    host: "{{priv_ip}}"
    port: 10255
    delay: 5
    connect_timeout: 2
    timeout: 1800
  changed_when: false

- name: get metadata api information
  uri:
    url: 'http://{{priv_ip}}:10255/pods'
    method: GET
    return_content: yes
  register: api_result
  changed_when: false

- name: ensure pods are downloading or present
  assert:
    that:
      - "'kube-apiserver-{{k8s_kubelet_hostname}}' in api_result.content"
      - "'kube-scheduler-{{k8s_kubelet_hostname}}' in api_result.content"
      - "'kube-controller-manager-{{k8s_kubelet_hostname}}' in api_result.content"
      - "'kube-proxy-{{k8s_kubelet_hostname}}' in api_result.content"
