---

- name: get kube-system namespaces info
  uri:
    url: 'http://127.0.0.1:8080/api/v1/namespaces'
    method: GET
    return_content: yes
  register: kubelet_info

- name: create the kube-system namespaces
  uri:
    url: 'http://127.0.0.1:8080/api/v1/namespaces'
    method: POST
    body: '{"apiVersion":"v1","kind":"Namespace","metadata":{"name":"kube-system"}}'
    body_format: json
    async: 300
    poll: 10
    register: kubelet_status
  when: kubelet_info.content.find('kube-system') == -1
