---

- name: generate k8s dns service and deployment files
  template:
    src: "{{k8s_template_dir}}/generate_yaml.j2"
    dest: "/tmp/{{item.dest}}"
    mode: 0644
  with_items:
    - { yaml: "{{k8s_dns_service}}", dest: 'kube-dns-svc.yaml' }
    - { yaml: "{{k8s_dns_deployment}}", dest: 'kube-dns-deployment.yaml' }
    - { yaml: "{{k8s_dns_deployment}}", dest: 'kube-dns-autoscaler.yaml' }

- name: create k8s dns service and replication controller
  command: "{{item}}"
  with_items:
    - "/opt/bin/kubectl apply -f /tmp/kube-dns-deployment.yaml"
    - "/opt/bin/kubectl apply -f /tmp/kube-dns-svc.yaml"
    - "/opt/bin/kubectl apply -f /tmp/kube-dns-autoscaler.yaml"
  changed_when: false