---

# Docker Configuration

- name: ensure docker systemd directory exist
  file:
    path: '/etc/systemd/system/docker.service.d'
    owner: root
    group: root
    mode: 0755
    state: directory

- name: configure Docker systemd options
  template:
    src: "{{k8s_template_dir}}/40-flannel.conf.j2"
    dest: '/etc/systemd/system/docker.service.d/40-flannel.conf'
    owner: root
    group: root
    owner: 0644
  notify: restart docker

- meta: flush_handlers
