#cloud-config

---
coreos:
    flannel:
        interface: 207.154.243.211
    units:
    -   command: start
        enable: true
        name: serial-getty@ttyS1.service
    -   command: start
        drop-ins:
        -   content: '[Service]

                Environment="ETCD_IMAGE_TAG=v3.2.4"

                Environment="ETCD_ADVERTISE_CLIENT_URLS=http://10.135.52.214:2379"

                Environment="ETCD_DISCOVERY=https://discovery.etcd.io/f356fc8b3c783af165bae8c675d06439"

                Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.135.52.214:2380"

                Environment="ETCD_LISTEN_CLIENT_URLS=http://127.0.0.1:2379,http://10.135.52.214:2379"

                Environment="ETCD_LISTEN_PEER_URLS=http://10.135.52.214:2380"

                '
            name: 40-etcd-cluster.conf
        enable: true
        name: etcd-member.service
    -   command: start
        drop-ins:
        -   content: '[Service]

                ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config ''{ "Network":
                "10.1.0.0/16" }''

                '
            name: 50-network-config.conf
        enable: true
        name: flanneld.service
    -   command: start
        content: '[Unit]

            Description=Prepare data drive

            Ater=dev-sdb.device

            After=dev-sdc.device

            Requires=dev-sdb.device

            Requires=dev-sdc.device

            ConditionPathExists=!/dev/md0

            [Service]

            Type=oneshot

            RemainAfterExit=yes

            ExecStart=/usr/sbin/wipefs -f /dev/sdb

            ExecStart=/usr/sbin/parted -s -a opt /dev/sdb mklabel gpt -- mkpart primary
            ext4 2048s -1

            ExecStart=/usr/sbin/parted -s /dev/sdb align-check optimal 1

            ExecStart=/usr/sbin/parted -s /dev/sdb set 1 raid on

            ExecStart=/usr/sbin/wipefs -f /dev/sdc

            ExecStart=/usr/sbin/parted -s -a opt /dev/sdc mklabel gpt -- mkpart primary
            ext4 2048s -1

            ExecStart=/usr/sbin/parted -s /dev/sdc align-check optimal 1

            ExecStart=/usr/sbin/parted -s /dev/sdc set 1 raid on

            ExecStart=/usr/sbin/mdadm --create --assume-clean --metadata=1.2 --verbose
            /dev/md0 --level=1 --raid-devices=2 /dev/sdb1 /dev/sdc1

            ExecStart=/usr/sbin/pvcreate -y /dev/md0

            ExecStart=/usr/sbin/vgcreate raid-vg /dev/md0

            ExecStart=/usr/sbin/lvcreate -l 100%FREE -n data raid-vg

            ExecStart=/usr/sbin/mkfs.ext4 -m 1 -F /dev/raid-vg/data

            '
        enable: true
        name: prepare-data-drive.service
    -   command: start
        content: '[Unit]

            After=prepare-data-drive.service

            Requires=prepare-data-drive.service

            [Mount]

            What=/dev/raid-vg/data

            Where=/mnt/data

            Type=ext4

            Options=rw,noatime,nodiratime,discard,data=ordered

            '
        enable: true
        name: mnt-data.mount
    -   content: '[Match]

            Name=eth0

            [Network]

            DHCP=true

            '
        name: 00-eth0.network
        runtime: true
    -   content: '[Match]

            Name=enp0s8

            [Network]

            Address=10.135.52.214/24

            '
        name: 00-enp0s8.network
        runtime: true
    -   command: start
        enable: true
        name: iptables-restore.service
    -   command: start
        content: '[Unit]

            Description=Set the time zone

            [Service]

            ExecStart=/usr/bin/timedatectl set-timezone UTC

            RemainAfterExit=yes

            Type=oneshot

            '
        enable: true
        name: settimezone.service
    -   command: restart
        name: systemd-modules-load.service
    -   command: restart
        name: systemd-sysctl.service
    -   command: start
        enable: true
        name: systemd-timesyncd.service
    -   command: stop
        enable: false
        name: mdmonitor.service
    -   command: start
        drop-ins:
        -   content: '[Unit]

                Requires=flanneld.service

                After=flanneld.service

                [Service]

                EnvironmentFile=/etc/kubernetes/cni/docker_opts_cni.env

                '
            name: 40-flannel.conf
        name: docker.service
    -   command: start
        content: '[Unit]

            Description=Docker Socket for the API

            After=mnt-data.mount

            Requires=mnt-data.mount

            [Socket]

            ListenStream=2375

            Service=docker.service

            BindIPv6Only=both

            [Install]

            WantedBy=sockets.target

            '
        enable: true
        name: docker-tcp.socket
    update:
        group: stable
        reboot-strategy: 'off'
hostname: 207.154.243.211
users:
-   name: core
    ssh-authorized-keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCBx0y9fFhiyqfl9E5tMfQvot91zrCBkxB2OrtERBTwIRQtg185ODoIshlHqMgEkNphoUXgynRn+xvL4e9Glh3pXzvyQt6jgMNeeQxobfJFLH2G0BksJMEMy1F7eGwZ+NfoXqTQCw+CGUI8FPxKATyuwUqAFI6AmbXEhET7rr7yNEjEGg+xdqebS3txflvzM7q72bumWsWCHTZCG+UqWNq+1IQMtjw9Y1nWUx2cPF0r9lSC5CEKic6ioq52cRAEhPUmR0jyNyKUZnSz7FMXyEbTlW0SeKCVf/S23YkhRlD+Z9cySNnx5mAdmpYaVgKTIKngMP/1N/oizgyYeqMnBdor
write_files:
-   content: 'TOOLBOX_DOCKER_IMAGE=debian

        TOOLBOX_DOCKER_TAG=stable

        '
    owner: core
    path: /home/core/.toolboxrc
-   content: 'DOCKER_OPT_BIP=""

        DOCKER_OPT_IPMASQ=""

        '
    path: /etc/kubernetes/cni/docker_opts_cni.env
-   content: nf_conntrack
    path: /etc/modules-load.d/nf.conf
-   content: net.ipv4.ip_forward=1
    path: /etc/sysctl.d/ipv4_forward.conf
-   content: vm.swappiness=1
    path: /etc/sysctl.d/swapiness.conf
-   content: vm.overcommit_memory=1
    path: /etc/sysctl.d/overcommit_memory.conf
-   content: vm.max_map_count=65535
    path: /etc/sysctl.d/max_map_count.conf
-   content: '*filter

        :INPUT ACCEPT [0:0]

        :FORWARD ACCEPT [0:0]

        :OUTPUT ACCEPT [0:0]

        -A INPUT -i lo -j ACCEPT

        -A INPUT -i enp0s8 -j ACCEPT

        -A INPUT -i tap0 -p all -j ACCEPT

        -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

        -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT

        -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT

        -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT

        -A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT

        -A INPUT -p icmp -m icmp --icmp-type 3 -j ACCEPT

        -A INPUT -p icmp -m icmp --icmp-type 11 -j ACCEPT

        -A INPUT -j DROP

        COMMIT

        '
    owner: root:root
    path: /var/lib/iptables/rules-save
    permissions: 420
